package com.edurda77.currencyconverter.model

import android.content.Context
import androidx.lifecycle.LiveData
import androidx.lifecycle.ViewModel
import com.edurda77.currencyconverter.model.Utility.isInternetAvailable

class ConvertorViewModel : ViewModel() {

    fun getGurrences(context: Context): LiveData<List<Currency>> {
        val currentFromDb = CurrencyRepoDbImpl(context)
        initData(context)
        return currentFromDb.getCurrencies()
    }

    private fun initData(context: Context) {
        val currentFromDb = CurrencyRepoDbImpl(context)
        if (context.isInternetAvailable()) {
            val dataOfValute = CurrencyUseCaseImpl().getMutableLiveData(context)
            if (currentFromDb.equals(null)) {
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.amd.charCode,
                        dataOfValute.value!!.valute.amd.nominal,
                        dataOfValute.value!!.valute.amd.name,
                        dataOfValute.value!!.valute.amd.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.amd.charCode,
                        dataOfValute.value!!.valute.amd.nominal,
                        dataOfValute.value!!.valute.amd.name,
                        dataOfValute.value!!.valute.amd.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.aud.charCode,
                        dataOfValute.value!!.valute.aud.nominal,
                        dataOfValute.value!!.valute.aud.name,
                        dataOfValute.value!!.valute.aud.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.azn.charCode,
                        dataOfValute.value!!.valute.azn.nominal,
                        dataOfValute.value!!.valute.azn.name,
                        dataOfValute.value!!.valute.azn.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.bgn.charCode,
                        dataOfValute.value!!.valute.bgn.nominal,
                        dataOfValute.value!!.valute.bgn.name,
                        dataOfValute.value!!.valute.bgn.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.brl.charCode,
                        dataOfValute.value!!.valute.brl.nominal,
                        dataOfValute.value!!.valute.brl.name,
                        dataOfValute.value!!.valute.brl.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.byn.charCode,
                        dataOfValute.value!!.valute.byn.nominal,
                        dataOfValute.value!!.valute.byn.name,
                        dataOfValute.value!!.valute.byn.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.cad.charCode,
                        dataOfValute.value!!.valute.cad.nominal,
                        dataOfValute.value!!.valute.cad.name,
                        dataOfValute.value!!.valute.cad.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.chf.charCode,
                        dataOfValute.value!!.valute.chf.nominal,
                        dataOfValute.value!!.valute.chf.name,
                        dataOfValute.value!!.valute.chf.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.cny.charCode,
                        dataOfValute.value!!.valute.cny.nominal,
                        dataOfValute.value!!.valute.cny.name,
                        dataOfValute.value!!.valute.cny.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.czk.charCode,
                        dataOfValute.value!!.valute.czk.nominal,
                        dataOfValute.value!!.valute.czk.name,
                        dataOfValute.value!!.valute.czk.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.dkk.charCode,
                        dataOfValute.value!!.valute.dkk.nominal,
                        dataOfValute.value!!.valute.dkk.name,
                        dataOfValute.value!!.valute.dkk.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.eur.charCode,
                        dataOfValute.value!!.valute.eur.nominal,
                        dataOfValute.value!!.valute.eur.name,
                        dataOfValute.value!!.valute.eur.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.gbp.charCode,
                        dataOfValute.value!!.valute.gbp.nominal,
                        dataOfValute.value!!.valute.gbp.name,
                        dataOfValute.value!!.valute.gbp.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.hkd.charCode,
                        dataOfValute.value!!.valute.hkd.nominal,
                        dataOfValute.value!!.valute.hkd.name,
                        dataOfValute.value!!.valute.hkd.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.huf.charCode,
                        dataOfValute.value!!.valute.huf.nominal,
                        dataOfValute.value!!.valute.huf.name,
                        dataOfValute.value!!.valute.huf.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.inr.charCode,
                        dataOfValute.value!!.valute.inr.nominal,
                        dataOfValute.value!!.valute.inr.name,
                        dataOfValute.value!!.valute.inr.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.jpy.charCode,
                        dataOfValute.value!!.valute.jpy.nominal,
                        dataOfValute.value!!.valute.jpy.name,
                        dataOfValute.value!!.valute.jpy.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.kgs.charCode,
                        dataOfValute.value!!.valute.kgs.nominal,
                        dataOfValute.value!!.valute.kgs.name,
                        dataOfValute.value!!.valute.kgs.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.krw.charCode,
                        dataOfValute.value!!.valute.krw.nominal,
                        dataOfValute.value!!.valute.krw.name,
                        dataOfValute.value!!.valute.krw.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.kzt.charCode,
                        dataOfValute.value!!.valute.kzt.nominal,
                        dataOfValute.value!!.valute.kzt.name,
                        dataOfValute.value!!.valute.kzt.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.mdl.charCode,
                        dataOfValute.value!!.valute.mdl.nominal,
                        dataOfValute.value!!.valute.mdl.name,
                        dataOfValute.value!!.valute.mdl.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.nok.charCode,
                        dataOfValute.value!!.valute.nok.nominal,
                        dataOfValute.value!!.valute.nok.name,
                        dataOfValute.value!!.valute.nok.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.pln.charCode,
                        dataOfValute.value!!.valute.pln.nominal,
                        dataOfValute.value!!.valute.pln.name,
                        dataOfValute.value!!.valute.pln.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.ron.charCode,
                        dataOfValute.value!!.valute.ron.nominal,
                        dataOfValute.value!!.valute.ron.name,
                        dataOfValute.value!!.valute.ron.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.sek.charCode,
                        dataOfValute.value!!.valute.sek.nominal,
                        dataOfValute.value!!.valute.sek.name,
                        dataOfValute.value!!.valute.sek.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.sgd.charCode,
                        dataOfValute.value!!.valute.sgd.nominal,
                        dataOfValute.value!!.valute.sgd.name,
                        dataOfValute.value!!.valute.sgd.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.tjs.charCode,
                        dataOfValute.value!!.valute.tjs.nominal,
                        dataOfValute.value!!.valute.tjs.name,
                        dataOfValute.value!!.valute.tjs.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.tmt.charCode,
                        dataOfValute.value!!.valute.tmt.nominal,
                        dataOfValute.value!!.valute.tmt.name,
                        dataOfValute.value!!.valute.tmt.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.tray.charCode,
                        dataOfValute.value!!.valute.tray.nominal,
                        dataOfValute.value!!.valute.tray.name,
                        dataOfValute.value!!.valute.tray.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.uah.charCode,
                        dataOfValute.value!!.valute.uah.nominal,
                        dataOfValute.value!!.valute.uah.name,
                        dataOfValute.value!!.valute.uah.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.usd.charCode,
                        dataOfValute.value!!.valute.usd.nominal,
                        dataOfValute.value!!.valute.usd.name,
                        dataOfValute.value!!.valute.usd.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.uzs.charCode,
                        dataOfValute.value!!.valute.uzs.nominal,
                        dataOfValute.value!!.valute.uzs.name,
                        dataOfValute.value!!.valute.uzs.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.xdr.charCode,
                        dataOfValute.value!!.valute.xdr.nominal,
                        dataOfValute.value!!.valute.xdr.name,
                        dataOfValute.value!!.valute.xdr.value
                    )
                )
                currentFromDb.add(
                    Currency(
                        dataOfValute.value!!.valute.zar.charCode,
                        dataOfValute.value!!.valute.zar.nominal,
                        dataOfValute.value!!.valute.zar.name,
                        dataOfValute.value!!.valute.zar.value
                    )
                )
            }
        }
    }
}