package com.edurda77.currencyconverter.model

import android.content.Context
import android.widget.Toast
import androidx.lifecycle.LiveData
import androidx.lifecycle.ViewModel
import com.edurda77.currencyconverter.model.Utility.isInternetAvailable

class ConvertorViewModel(private val context: Context) : ViewModel() {


    fun getGurrences(): LiveData<List<Currency>> {
        val currentFromDb = CurrencyRepoDbImpl(context)
        //initData()
        return currentFromDb.getCurrencies()
    }

    fun initData() {
        val currentFromDb = CurrencyRepoDbImpl(context)
        CurrencyUseCaseImpl().getCurrenciesAsync(
            onSuccess = {
                if (currentFromDb.equals(null)) {
                    if (it != null) {
                        currentFromDb.add(
                            Currency(
                                it.valute.amd.charCode,
                                it.valute.amd.nominal,
                                it.valute.amd.name,
                                it.valute.amd.value
                            )
                        )

                        currentFromDb.add(
                            Currency(
                                it.valute.amd.charCode,
                                it.valute.amd.nominal,
                                it.valute.amd.name,
                                it.valute.amd.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.aud.charCode,
                                it.valute.aud.nominal,
                                it.valute.aud.name,
                                it.valute.aud.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.azn.charCode,
                                it.valute.azn.nominal,
                                it.valute.azn.name,
                                it.valute.azn.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.bgn.charCode,
                                it.valute.bgn.nominal,
                                it.valute.bgn.name,
                                it.valute.bgn.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.brl.charCode,
                                it.valute.brl.nominal,
                                it.valute.brl.name,
                                it.valute.brl.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.byn.charCode,
                                it.valute.byn.nominal,
                                it.valute.byn.name,
                                it.valute.byn.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.cad.charCode,
                                it.valute.cad.nominal,
                                it.valute.cad.name,
                                it.valute.cad.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.chf.charCode,
                                it.valute.chf.nominal,
                                it.valute.chf.name,
                                it.valute.chf.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.cny.charCode,
                                it.valute.cny.nominal,
                                it.valute.cny.name,
                                it.valute.cny.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.czk.charCode,
                                it.valute.czk.nominal,
                                it.valute.czk.name,
                                it.valute.czk.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.dkk.charCode,
                                it.valute.dkk.nominal,
                                it.valute.dkk.name,
                                it.valute.dkk.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.eur.charCode,
                                it.valute.eur.nominal,
                                it.valute.eur.name,
                                it.valute.eur.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.gbp.charCode,
                                it.valute.gbp.nominal,
                                it.valute.gbp.name,
                                it.valute.gbp.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.hkd.charCode,
                                it.valute.hkd.nominal,
                                it.valute.hkd.name,
                                it.valute.hkd.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.huf.charCode,
                                it.valute.huf.nominal,
                                it.valute.huf.name,
                                it.valute.huf.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.inr.charCode,
                                it.valute.inr.nominal,
                                it.valute.inr.name,
                                it.valute.inr.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.jpy.charCode,
                                it.valute.jpy.nominal,
                                it.valute.jpy.name,
                                it.valute.jpy.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.kgs.charCode,
                                it.valute.kgs.nominal,
                                it.valute.kgs.name,
                                it.valute.kgs.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.krw.charCode,
                                it.valute.krw.nominal,
                                it.valute.krw.name,
                                it.valute.krw.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.kzt.charCode,
                                it.valute.kzt.nominal,
                                it.valute.kzt.name,
                                it.valute.kzt.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.mdl.charCode,
                                it.valute.mdl.nominal,
                                it.valute.mdl.name,
                                it.valute.mdl.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.nok.charCode,
                                it.valute.nok.nominal,
                                it.valute.nok.name,
                                it.valute.nok.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.pln.charCode,
                                it.valute.pln.nominal,
                                it.valute.pln.name,
                                it.valute.pln.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.ron.charCode,
                                it.valute.ron.nominal,
                                it.valute.ron.name,
                                it.valute.ron.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.sek.charCode,
                                it.valute.sek.nominal,
                                it.valute.sek.name,
                                it.valute.sek.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.sgd.charCode,
                                it.valute.sgd.nominal,
                                it.valute.sgd.name,
                                it.valute.sgd.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.tjs.charCode,
                                it.valute.tjs.nominal,
                                it.valute.tjs.name,
                                it.valute.tjs.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.tmt.charCode,
                                it.valute.tmt.nominal,
                                it.valute.tmt.name,
                                it.valute.tmt.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.tray.charCode,
                                it.valute.tray.nominal,
                                it.valute.tray.name,
                                it.valute.tray.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.uah.charCode,
                                it.valute.uah.nominal,
                                it.valute.uah.name,
                                it.valute.uah.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.usd.charCode,
                                it.valute.usd.nominal,
                                it.valute.usd.name,
                                it.valute.usd.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.uzs.charCode,
                                it.valute.uzs.nominal,
                                it.valute.uzs.name,
                                it.valute.uzs.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.xdr.charCode,
                                it.valute.xdr.nominal,
                                it.valute.xdr.name,
                                it.valute.xdr.value
                            )
                        )
                        currentFromDb.add(
                            Currency(
                                it.valute.zar.charCode,
                                it.valute.zar.nominal,
                                it.valute.zar.name,
                                it.valute.zar.value
                            )
                        )
                    }
                }
            },
        onError = {Toast.makeText(context, "Ошибка", Toast.LENGTH_LONG).show()})
    }


}